# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='docker_image',
            field=models.CharField(max_length=50, verbose_name='Docker Image'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Algorithm Name'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Author Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='organization',
            field=models.CharField(max_length=200, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Paper Title'),
        ),
    ]
