# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20160622_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='join_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 19, 22, 45, 26, 396760, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
