# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_author_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
