# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20160728_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='contributor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='public.Contributor'),
        ),
    ]
