# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20160728_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Contributor Name'),
        ),
    ]
