# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_auto_20160730_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='organization_website',
            field=models.URLField(blank=True, null=True, verbose_name='Organization Website'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='personal_website',
            field=models.URLField(blank=True, null=True, verbose_name='Personal Website'),
        ),
    ]
