# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_auto_20160803_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(default='NEW_ALGORITHM', max_length=200, verbose_name='Algorithm Name'),
        ),
    ]
