# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_auto_20160803_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 3, 17, 59, 25, 679478, tzinfo=utc), verbose_name='Date Submitted'),
            preserve_default=False,
        ),
    ]
