# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_auto_20160803_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='submit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 3, 18, 3, 15, 469010), verbose_name='Date Submitted'),
        ),
    ]
