# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_auto_20160803_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='submit_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Submitted'),
        ),
    ]
