# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_auto_20160803_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='new_version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='A new versions'),
        ),
    ]
