# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0019_auto_20160815_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Workflow Name')),
                ('description', models.CharField(max_length=10000, verbose_name='Description')),
                ('workflow_json', models.TextField(verbose_name='Workflow JSON')),
                ('screenshot_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Screenshot Path')),
                ('file_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='File Path')),
                ('submit_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Submitted')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Workflow Availability')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Published')),
                ('contributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.Contributor')),
            ],
        ),
    ]
