# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0020_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='versions',
            field=models.CharField(default="['latest']", max_length=200, verbose_name='Algorithm Versions'),
        ),
    ]
