# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0021_auto_20160817_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
