# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunningContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=200, verbose_name='Visitor ID')),
                ('docker_image', models.CharField(max_length=200, verbose_name='Docker Image')),
                ('container_id', models.CharField(max_length=200, verbose_name='Container ID')),
                ('port_number', models.IntegerField(verbose_name='Port Number')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
